# -*- coding: utf-8 -*-
## problem 29
## If they are then placed in numerical order,
## with any repeats removed, we get the following sequence
## of 15 distinct terms:
##
## 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
##
## How many distinct terms are in the sequence
## generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

import math

# Constants
max_a = 101
max_b = 101

myList = []

# create a list of all numbers
for n in range(2,max_a):
    for p in range(2,max_b):
        myList.append(pow(n,p))

#print myList
print(len(myList))

myList2 = []
myList2.append(myList[0])

# remove numbers that reapire
for i in range(1,len(myList)):
    temp= False
    for j in range(0,i):
        if myList[i] == myList[j]:
            temp = True
            break
    if temp == False:
        myList2.append(myList[i])

#
print(myList2)
print(len(myList2))

